server:
  tomcat:
    threads:
      max: 200
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: #데이터베이스 주소
    username: #아이디
    password: #패스워드
  jpa:
    entityManagerFactory:
      name: hit
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
